import { CreateUserFromGoogleData, CreateUserFromGoogleVariables, SetUserTypeData, SetUserTypeVariables, SelectMyColorSchemeData, SelectMyColorSchemeVariables, ClearMyColorSchemeData, SelectMyPerformanceModeData, SelectMyPerformanceModeVariables, SelectMyBackgroundOpacityData, SelectMyBackgroundOpacityVariables, SelectMyExternalAccountLinkTemplateData, SelectMyExternalAccountLinkTemplateVariables, SelectMyCardStyleData, SelectMyCardStyleVariables, SelectMySquareCornersData, SelectMySquareCornersVariables, SelectMyBordersEnabledData, SelectMyBordersEnabledVariables, SelectMyCategoryColorsEnabledData, SelectMyCategoryColorsEnabledVariables, SelectMyCurrencyData, SelectMyCurrencyVariables, CreateFamilyMemberData, CreateFamilyMemberVariables, UpdateFamilyMemberData, UpdateFamilyMemberVariables, RenameFamilyMemberData, RenameFamilyMemberVariables, DeleteFamilyMemberData, DeleteFamilyMemberVariables, UpsertCategoryData, UpsertCategoryVariables, UpdateCategoryData, UpdateCategoryVariables, CreateTransactionData, CreateTransactionVariables, UpdateTransactionData, UpdateTransactionVariables, UpdateTransactionClearCategoryData, UpdateTransactionClearCategoryVariables, MarkTransactionPostedData, MarkTransactionPostedVariables, MarkTransactionProjectedData, MarkTransactionProjectedVariables, DeleteTransactionData, DeleteTransactionVariables, CreateFamilyData, CreateFamilyVariables, RequestToJoinFamilyData, RequestToJoinFamilyVariables, ApproveJoinRequestData, ApproveJoinRequestVariables, DenyJoinRequestData, DenyJoinRequestVariables, CancelMyJoinRequestData, CancelMyJoinRequestVariables, LeaveMyFamilyData, LeaveMyFamilyVariables, RegenerateFamilyInviteCodeData, RegenerateFamilyInviteCodeVariables, CreateUserSettingForUserData, CreateUserSettingForUserVariables, ListUsersData, GetMyUserData, ListColorSchemesData, ListUserTypesData, GetUserAccessByGoogleUidData, GetUserAccessByGoogleUidVariables, GetUserProvisioningByGoogleUidData, GetUserProvisioningByGoogleUidVariables, ListFamilyMembersData, ListFamilyMembersVariables, ListCategoriesData, ListCategoriesVariables, ListTransactionsByFamilyMemberData, ListTransactionsByFamilyMemberVariables, ListMyTransactionsData, ListMyTransactionsVariables, ListMyTransactionsByDateRangeData, ListMyTransactionsByDateRangeVariables, GetFamilyByInviteCodeData, GetFamilyByInviteCodeVariables, GetMyFamilyDetailData, GetMyJoinRequestsData } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useCreateUserFromGoogle(options?: useDataConnectMutationOptions<CreateUserFromGoogleData, FirebaseError, CreateUserFromGoogleVariables>): UseDataConnectMutationResult<CreateUserFromGoogleData, CreateUserFromGoogleVariables>;
export function useCreateUserFromGoogle(dc: DataConnect, options?: useDataConnectMutationOptions<CreateUserFromGoogleData, FirebaseError, CreateUserFromGoogleVariables>): UseDataConnectMutationResult<CreateUserFromGoogleData, CreateUserFromGoogleVariables>;

export function useSetUserType(options?: useDataConnectMutationOptions<SetUserTypeData, FirebaseError, SetUserTypeVariables>): UseDataConnectMutationResult<SetUserTypeData, SetUserTypeVariables>;
export function useSetUserType(dc: DataConnect, options?: useDataConnectMutationOptions<SetUserTypeData, FirebaseError, SetUserTypeVariables>): UseDataConnectMutationResult<SetUserTypeData, SetUserTypeVariables>;

export function useSelectMyColorScheme(options?: useDataConnectMutationOptions<SelectMyColorSchemeData, FirebaseError, SelectMyColorSchemeVariables>): UseDataConnectMutationResult<SelectMyColorSchemeData, SelectMyColorSchemeVariables>;
export function useSelectMyColorScheme(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyColorSchemeData, FirebaseError, SelectMyColorSchemeVariables>): UseDataConnectMutationResult<SelectMyColorSchemeData, SelectMyColorSchemeVariables>;

export function useClearMyColorScheme(options?: useDataConnectMutationOptions<ClearMyColorSchemeData, FirebaseError, void>): UseDataConnectMutationResult<ClearMyColorSchemeData, undefined>;
export function useClearMyColorScheme(dc: DataConnect, options?: useDataConnectMutationOptions<ClearMyColorSchemeData, FirebaseError, void>): UseDataConnectMutationResult<ClearMyColorSchemeData, undefined>;

export function useSelectMyPerformanceMode(options?: useDataConnectMutationOptions<SelectMyPerformanceModeData, FirebaseError, SelectMyPerformanceModeVariables>): UseDataConnectMutationResult<SelectMyPerformanceModeData, SelectMyPerformanceModeVariables>;
export function useSelectMyPerformanceMode(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyPerformanceModeData, FirebaseError, SelectMyPerformanceModeVariables>): UseDataConnectMutationResult<SelectMyPerformanceModeData, SelectMyPerformanceModeVariables>;

export function useSelectMyBackgroundOpacity(options?: useDataConnectMutationOptions<SelectMyBackgroundOpacityData, FirebaseError, SelectMyBackgroundOpacityVariables>): UseDataConnectMutationResult<SelectMyBackgroundOpacityData, SelectMyBackgroundOpacityVariables>;
export function useSelectMyBackgroundOpacity(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyBackgroundOpacityData, FirebaseError, SelectMyBackgroundOpacityVariables>): UseDataConnectMutationResult<SelectMyBackgroundOpacityData, SelectMyBackgroundOpacityVariables>;

export function useSelectMyExternalAccountLinkTemplate(options?: useDataConnectMutationOptions<SelectMyExternalAccountLinkTemplateData, FirebaseError, SelectMyExternalAccountLinkTemplateVariables | void>): UseDataConnectMutationResult<SelectMyExternalAccountLinkTemplateData, SelectMyExternalAccountLinkTemplateVariables>;
export function useSelectMyExternalAccountLinkTemplate(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyExternalAccountLinkTemplateData, FirebaseError, SelectMyExternalAccountLinkTemplateVariables | void>): UseDataConnectMutationResult<SelectMyExternalAccountLinkTemplateData, SelectMyExternalAccountLinkTemplateVariables>;

export function useSelectMyCardStyle(options?: useDataConnectMutationOptions<SelectMyCardStyleData, FirebaseError, SelectMyCardStyleVariables>): UseDataConnectMutationResult<SelectMyCardStyleData, SelectMyCardStyleVariables>;
export function useSelectMyCardStyle(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyCardStyleData, FirebaseError, SelectMyCardStyleVariables>): UseDataConnectMutationResult<SelectMyCardStyleData, SelectMyCardStyleVariables>;

export function useSelectMySquareCorners(options?: useDataConnectMutationOptions<SelectMySquareCornersData, FirebaseError, SelectMySquareCornersVariables>): UseDataConnectMutationResult<SelectMySquareCornersData, SelectMySquareCornersVariables>;
export function useSelectMySquareCorners(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMySquareCornersData, FirebaseError, SelectMySquareCornersVariables>): UseDataConnectMutationResult<SelectMySquareCornersData, SelectMySquareCornersVariables>;

export function useSelectMyBordersEnabled(options?: useDataConnectMutationOptions<SelectMyBordersEnabledData, FirebaseError, SelectMyBordersEnabledVariables>): UseDataConnectMutationResult<SelectMyBordersEnabledData, SelectMyBordersEnabledVariables>;
export function useSelectMyBordersEnabled(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyBordersEnabledData, FirebaseError, SelectMyBordersEnabledVariables>): UseDataConnectMutationResult<SelectMyBordersEnabledData, SelectMyBordersEnabledVariables>;

export function useSelectMyCategoryColorsEnabled(options?: useDataConnectMutationOptions<SelectMyCategoryColorsEnabledData, FirebaseError, SelectMyCategoryColorsEnabledVariables>): UseDataConnectMutationResult<SelectMyCategoryColorsEnabledData, SelectMyCategoryColorsEnabledVariables>;
export function useSelectMyCategoryColorsEnabled(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyCategoryColorsEnabledData, FirebaseError, SelectMyCategoryColorsEnabledVariables>): UseDataConnectMutationResult<SelectMyCategoryColorsEnabledData, SelectMyCategoryColorsEnabledVariables>;

export function useSelectMyCurrency(options?: useDataConnectMutationOptions<SelectMyCurrencyData, FirebaseError, SelectMyCurrencyVariables>): UseDataConnectMutationResult<SelectMyCurrencyData, SelectMyCurrencyVariables>;
export function useSelectMyCurrency(dc: DataConnect, options?: useDataConnectMutationOptions<SelectMyCurrencyData, FirebaseError, SelectMyCurrencyVariables>): UseDataConnectMutationResult<SelectMyCurrencyData, SelectMyCurrencyVariables>;

export function useCreateFamilyMember(options?: useDataConnectMutationOptions<CreateFamilyMemberData, FirebaseError, CreateFamilyMemberVariables>): UseDataConnectMutationResult<CreateFamilyMemberData, CreateFamilyMemberVariables>;
export function useCreateFamilyMember(dc: DataConnect, options?: useDataConnectMutationOptions<CreateFamilyMemberData, FirebaseError, CreateFamilyMemberVariables>): UseDataConnectMutationResult<CreateFamilyMemberData, CreateFamilyMemberVariables>;

export function useUpdateFamilyMember(options?: useDataConnectMutationOptions<UpdateFamilyMemberData, FirebaseError, UpdateFamilyMemberVariables>): UseDataConnectMutationResult<UpdateFamilyMemberData, UpdateFamilyMemberVariables>;
export function useUpdateFamilyMember(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateFamilyMemberData, FirebaseError, UpdateFamilyMemberVariables>): UseDataConnectMutationResult<UpdateFamilyMemberData, UpdateFamilyMemberVariables>;

export function useRenameFamilyMember(options?: useDataConnectMutationOptions<RenameFamilyMemberData, FirebaseError, RenameFamilyMemberVariables>): UseDataConnectMutationResult<RenameFamilyMemberData, RenameFamilyMemberVariables>;
export function useRenameFamilyMember(dc: DataConnect, options?: useDataConnectMutationOptions<RenameFamilyMemberData, FirebaseError, RenameFamilyMemberVariables>): UseDataConnectMutationResult<RenameFamilyMemberData, RenameFamilyMemberVariables>;

export function useDeleteFamilyMember(options?: useDataConnectMutationOptions<DeleteFamilyMemberData, FirebaseError, DeleteFamilyMemberVariables>): UseDataConnectMutationResult<DeleteFamilyMemberData, DeleteFamilyMemberVariables>;
export function useDeleteFamilyMember(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteFamilyMemberData, FirebaseError, DeleteFamilyMemberVariables>): UseDataConnectMutationResult<DeleteFamilyMemberData, DeleteFamilyMemberVariables>;

export function useUpsertCategory(options?: useDataConnectMutationOptions<UpsertCategoryData, FirebaseError, UpsertCategoryVariables>): UseDataConnectMutationResult<UpsertCategoryData, UpsertCategoryVariables>;
export function useUpsertCategory(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertCategoryData, FirebaseError, UpsertCategoryVariables>): UseDataConnectMutationResult<UpsertCategoryData, UpsertCategoryVariables>;

export function useUpdateCategory(options?: useDataConnectMutationOptions<UpdateCategoryData, FirebaseError, UpdateCategoryVariables>): UseDataConnectMutationResult<UpdateCategoryData, UpdateCategoryVariables>;
export function useUpdateCategory(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateCategoryData, FirebaseError, UpdateCategoryVariables>): UseDataConnectMutationResult<UpdateCategoryData, UpdateCategoryVariables>;

export function useCreateTransaction(options?: useDataConnectMutationOptions<CreateTransactionData, FirebaseError, CreateTransactionVariables>): UseDataConnectMutationResult<CreateTransactionData, CreateTransactionVariables>;
export function useCreateTransaction(dc: DataConnect, options?: useDataConnectMutationOptions<CreateTransactionData, FirebaseError, CreateTransactionVariables>): UseDataConnectMutationResult<CreateTransactionData, CreateTransactionVariables>;

export function useUpdateTransaction(options?: useDataConnectMutationOptions<UpdateTransactionData, FirebaseError, UpdateTransactionVariables>): UseDataConnectMutationResult<UpdateTransactionData, UpdateTransactionVariables>;
export function useUpdateTransaction(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateTransactionData, FirebaseError, UpdateTransactionVariables>): UseDataConnectMutationResult<UpdateTransactionData, UpdateTransactionVariables>;

export function useUpdateTransactionClearCategory(options?: useDataConnectMutationOptions<UpdateTransactionClearCategoryData, FirebaseError, UpdateTransactionClearCategoryVariables>): UseDataConnectMutationResult<UpdateTransactionClearCategoryData, UpdateTransactionClearCategoryVariables>;
export function useUpdateTransactionClearCategory(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateTransactionClearCategoryData, FirebaseError, UpdateTransactionClearCategoryVariables>): UseDataConnectMutationResult<UpdateTransactionClearCategoryData, UpdateTransactionClearCategoryVariables>;

export function useMarkTransactionPosted(options?: useDataConnectMutationOptions<MarkTransactionPostedData, FirebaseError, MarkTransactionPostedVariables>): UseDataConnectMutationResult<MarkTransactionPostedData, MarkTransactionPostedVariables>;
export function useMarkTransactionPosted(dc: DataConnect, options?: useDataConnectMutationOptions<MarkTransactionPostedData, FirebaseError, MarkTransactionPostedVariables>): UseDataConnectMutationResult<MarkTransactionPostedData, MarkTransactionPostedVariables>;

export function useMarkTransactionProjected(options?: useDataConnectMutationOptions<MarkTransactionProjectedData, FirebaseError, MarkTransactionProjectedVariables>): UseDataConnectMutationResult<MarkTransactionProjectedData, MarkTransactionProjectedVariables>;
export function useMarkTransactionProjected(dc: DataConnect, options?: useDataConnectMutationOptions<MarkTransactionProjectedData, FirebaseError, MarkTransactionProjectedVariables>): UseDataConnectMutationResult<MarkTransactionProjectedData, MarkTransactionProjectedVariables>;

export function useDeleteTransaction(options?: useDataConnectMutationOptions<DeleteTransactionData, FirebaseError, DeleteTransactionVariables>): UseDataConnectMutationResult<DeleteTransactionData, DeleteTransactionVariables>;
export function useDeleteTransaction(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteTransactionData, FirebaseError, DeleteTransactionVariables>): UseDataConnectMutationResult<DeleteTransactionData, DeleteTransactionVariables>;

export function useCreateFamily(options?: useDataConnectMutationOptions<CreateFamilyData, FirebaseError, CreateFamilyVariables>): UseDataConnectMutationResult<CreateFamilyData, CreateFamilyVariables>;
export function useCreateFamily(dc: DataConnect, options?: useDataConnectMutationOptions<CreateFamilyData, FirebaseError, CreateFamilyVariables>): UseDataConnectMutationResult<CreateFamilyData, CreateFamilyVariables>;

export function useRequestToJoinFamily(options?: useDataConnectMutationOptions<RequestToJoinFamilyData, FirebaseError, RequestToJoinFamilyVariables>): UseDataConnectMutationResult<RequestToJoinFamilyData, RequestToJoinFamilyVariables>;
export function useRequestToJoinFamily(dc: DataConnect, options?: useDataConnectMutationOptions<RequestToJoinFamilyData, FirebaseError, RequestToJoinFamilyVariables>): UseDataConnectMutationResult<RequestToJoinFamilyData, RequestToJoinFamilyVariables>;

export function useApproveJoinRequest(options?: useDataConnectMutationOptions<ApproveJoinRequestData, FirebaseError, ApproveJoinRequestVariables>): UseDataConnectMutationResult<ApproveJoinRequestData, ApproveJoinRequestVariables>;
export function useApproveJoinRequest(dc: DataConnect, options?: useDataConnectMutationOptions<ApproveJoinRequestData, FirebaseError, ApproveJoinRequestVariables>): UseDataConnectMutationResult<ApproveJoinRequestData, ApproveJoinRequestVariables>;

export function useDenyJoinRequest(options?: useDataConnectMutationOptions<DenyJoinRequestData, FirebaseError, DenyJoinRequestVariables>): UseDataConnectMutationResult<DenyJoinRequestData, DenyJoinRequestVariables>;
export function useDenyJoinRequest(dc: DataConnect, options?: useDataConnectMutationOptions<DenyJoinRequestData, FirebaseError, DenyJoinRequestVariables>): UseDataConnectMutationResult<DenyJoinRequestData, DenyJoinRequestVariables>;

export function useCancelMyJoinRequest(options?: useDataConnectMutationOptions<CancelMyJoinRequestData, FirebaseError, CancelMyJoinRequestVariables>): UseDataConnectMutationResult<CancelMyJoinRequestData, CancelMyJoinRequestVariables>;
export function useCancelMyJoinRequest(dc: DataConnect, options?: useDataConnectMutationOptions<CancelMyJoinRequestData, FirebaseError, CancelMyJoinRequestVariables>): UseDataConnectMutationResult<CancelMyJoinRequestData, CancelMyJoinRequestVariables>;

export function useLeaveMyFamily(options?: useDataConnectMutationOptions<LeaveMyFamilyData, FirebaseError, LeaveMyFamilyVariables>): UseDataConnectMutationResult<LeaveMyFamilyData, LeaveMyFamilyVariables>;
export function useLeaveMyFamily(dc: DataConnect, options?: useDataConnectMutationOptions<LeaveMyFamilyData, FirebaseError, LeaveMyFamilyVariables>): UseDataConnectMutationResult<LeaveMyFamilyData, LeaveMyFamilyVariables>;

export function useRegenerateFamilyInviteCode(options?: useDataConnectMutationOptions<RegenerateFamilyInviteCodeData, FirebaseError, RegenerateFamilyInviteCodeVariables>): UseDataConnectMutationResult<RegenerateFamilyInviteCodeData, RegenerateFamilyInviteCodeVariables>;
export function useRegenerateFamilyInviteCode(dc: DataConnect, options?: useDataConnectMutationOptions<RegenerateFamilyInviteCodeData, FirebaseError, RegenerateFamilyInviteCodeVariables>): UseDataConnectMutationResult<RegenerateFamilyInviteCodeData, RegenerateFamilyInviteCodeVariables>;

export function useCreateUserSettingForUser(options?: useDataConnectMutationOptions<CreateUserSettingForUserData, FirebaseError, CreateUserSettingForUserVariables>): UseDataConnectMutationResult<CreateUserSettingForUserData, CreateUserSettingForUserVariables>;
export function useCreateUserSettingForUser(dc: DataConnect, options?: useDataConnectMutationOptions<CreateUserSettingForUserData, FirebaseError, CreateUserSettingForUserVariables>): UseDataConnectMutationResult<CreateUserSettingForUserData, CreateUserSettingForUserVariables>;

export function useListUsers(options?: useDataConnectQueryOptions<ListUsersData>): UseDataConnectQueryResult<ListUsersData, undefined>;
export function useListUsers(dc: DataConnect, options?: useDataConnectQueryOptions<ListUsersData>): UseDataConnectQueryResult<ListUsersData, undefined>;

export function useGetMyUser(options?: useDataConnectQueryOptions<GetMyUserData>): UseDataConnectQueryResult<GetMyUserData, undefined>;
export function useGetMyUser(dc: DataConnect, options?: useDataConnectQueryOptions<GetMyUserData>): UseDataConnectQueryResult<GetMyUserData, undefined>;

export function useListColorSchemes(options?: useDataConnectQueryOptions<ListColorSchemesData>): UseDataConnectQueryResult<ListColorSchemesData, undefined>;
export function useListColorSchemes(dc: DataConnect, options?: useDataConnectQueryOptions<ListColorSchemesData>): UseDataConnectQueryResult<ListColorSchemesData, undefined>;

export function useListUserTypes(options?: useDataConnectQueryOptions<ListUserTypesData>): UseDataConnectQueryResult<ListUserTypesData, undefined>;
export function useListUserTypes(dc: DataConnect, options?: useDataConnectQueryOptions<ListUserTypesData>): UseDataConnectQueryResult<ListUserTypesData, undefined>;

export function useGetUserAccessByGoogleUid(vars: GetUserAccessByGoogleUidVariables, options?: useDataConnectQueryOptions<GetUserAccessByGoogleUidData>): UseDataConnectQueryResult<GetUserAccessByGoogleUidData, GetUserAccessByGoogleUidVariables>;
export function useGetUserAccessByGoogleUid(dc: DataConnect, vars: GetUserAccessByGoogleUidVariables, options?: useDataConnectQueryOptions<GetUserAccessByGoogleUidData>): UseDataConnectQueryResult<GetUserAccessByGoogleUidData, GetUserAccessByGoogleUidVariables>;

export function useGetUserProvisioningByGoogleUid(vars: GetUserProvisioningByGoogleUidVariables, options?: useDataConnectQueryOptions<GetUserProvisioningByGoogleUidData>): UseDataConnectQueryResult<GetUserProvisioningByGoogleUidData, GetUserProvisioningByGoogleUidVariables>;
export function useGetUserProvisioningByGoogleUid(dc: DataConnect, vars: GetUserProvisioningByGoogleUidVariables, options?: useDataConnectQueryOptions<GetUserProvisioningByGoogleUidData>): UseDataConnectQueryResult<GetUserProvisioningByGoogleUidData, GetUserProvisioningByGoogleUidVariables>;

export function useListFamilyMembers(vars?: ListFamilyMembersVariables, options?: useDataConnectQueryOptions<ListFamilyMembersData>): UseDataConnectQueryResult<ListFamilyMembersData, ListFamilyMembersVariables>;
export function useListFamilyMembers(dc: DataConnect, vars?: ListFamilyMembersVariables, options?: useDataConnectQueryOptions<ListFamilyMembersData>): UseDataConnectQueryResult<ListFamilyMembersData, ListFamilyMembersVariables>;

export function useListCategories(vars?: ListCategoriesVariables, options?: useDataConnectQueryOptions<ListCategoriesData>): UseDataConnectQueryResult<ListCategoriesData, ListCategoriesVariables>;
export function useListCategories(dc: DataConnect, vars?: ListCategoriesVariables, options?: useDataConnectQueryOptions<ListCategoriesData>): UseDataConnectQueryResult<ListCategoriesData, ListCategoriesVariables>;

export function useListTransactionsByFamilyMember(vars: ListTransactionsByFamilyMemberVariables, options?: useDataConnectQueryOptions<ListTransactionsByFamilyMemberData>): UseDataConnectQueryResult<ListTransactionsByFamilyMemberData, ListTransactionsByFamilyMemberVariables>;
export function useListTransactionsByFamilyMember(dc: DataConnect, vars: ListTransactionsByFamilyMemberVariables, options?: useDataConnectQueryOptions<ListTransactionsByFamilyMemberData>): UseDataConnectQueryResult<ListTransactionsByFamilyMemberData, ListTransactionsByFamilyMemberVariables>;

export function useListMyTransactions(vars?: ListMyTransactionsVariables, options?: useDataConnectQueryOptions<ListMyTransactionsData>): UseDataConnectQueryResult<ListMyTransactionsData, ListMyTransactionsVariables>;
export function useListMyTransactions(dc: DataConnect, vars?: ListMyTransactionsVariables, options?: useDataConnectQueryOptions<ListMyTransactionsData>): UseDataConnectQueryResult<ListMyTransactionsData, ListMyTransactionsVariables>;

export function useListMyTransactionsByDateRange(vars: ListMyTransactionsByDateRangeVariables, options?: useDataConnectQueryOptions<ListMyTransactionsByDateRangeData>): UseDataConnectQueryResult<ListMyTransactionsByDateRangeData, ListMyTransactionsByDateRangeVariables>;
export function useListMyTransactionsByDateRange(dc: DataConnect, vars: ListMyTransactionsByDateRangeVariables, options?: useDataConnectQueryOptions<ListMyTransactionsByDateRangeData>): UseDataConnectQueryResult<ListMyTransactionsByDateRangeData, ListMyTransactionsByDateRangeVariables>;

export function useGetFamilyByInviteCode(vars: GetFamilyByInviteCodeVariables, options?: useDataConnectQueryOptions<GetFamilyByInviteCodeData>): UseDataConnectQueryResult<GetFamilyByInviteCodeData, GetFamilyByInviteCodeVariables>;
export function useGetFamilyByInviteCode(dc: DataConnect, vars: GetFamilyByInviteCodeVariables, options?: useDataConnectQueryOptions<GetFamilyByInviteCodeData>): UseDataConnectQueryResult<GetFamilyByInviteCodeData, GetFamilyByInviteCodeVariables>;

export function useGetMyFamilyDetail(options?: useDataConnectQueryOptions<GetMyFamilyDetailData>): UseDataConnectQueryResult<GetMyFamilyDetailData, undefined>;
export function useGetMyFamilyDetail(dc: DataConnect, options?: useDataConnectQueryOptions<GetMyFamilyDetailData>): UseDataConnectQueryResult<GetMyFamilyDetailData, undefined>;

export function useGetMyJoinRequests(options?: useDataConnectQueryOptions<GetMyJoinRequestsData>): UseDataConnectQueryResult<GetMyJoinRequestsData, undefined>;
export function useGetMyJoinRequests(dc: DataConnect, options?: useDataConnectQueryOptions<GetMyJoinRequestsData>): UseDataConnectQueryResult<GetMyJoinRequestsData, undefined>;
