extend type BankAccount {
  """
  ✨ Implicit foreign key field based on `BankAccount`.`familyMember`. It must match the value of `FamilyMember`.`id`. See `@ref` for how to customize it.
  """
  familyMemberId: UUID @fdc_generated(from: "BankAccount.familyMember", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `BankAccount`.`plaidItem`. It must match the value of `PlaidItem`.`id`. See `@ref` for how to customize it.
  """
  plaidItemId: UUID! @fdc_generated(from: "BankAccount.plaidItem", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `BankAccount`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "BankAccount.user", purpose: IMPLICIT_REF_FIELD)
}
extend type FamilyMember {
  """
  ✨ Implicit foreign key field based on `FamilyMember`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "FamilyMember.user", purpose: IMPLICIT_REF_FIELD)
}
extend type PlaidItem {
  """
  ✨ Implicit foreign key field based on `PlaidItem`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "PlaidItem.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Theme {
  """
  ✨ Implicit foreign key field based on `Theme`.`colorScheme`. It must match the value of `ColorScheme`.`id`. See `@ref` for how to customize it.
  """
  colorSchemeId: UUID! @fdc_generated(from: "Theme.colorScheme", purpose: IMPLICIT_REF_FIELD)
}
extend type Transaction {
  """
  ✨ Implicit foreign key field based on `Transaction`.`bankAccount`. It must match the value of `BankAccount`.`id`. See `@ref` for how to customize it.
  """
  bankAccountId: UUID @fdc_generated(from: "Transaction.bankAccount", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Transaction`.`category`. It must match the value of `Category`.`name`. See `@ref` for how to customize it.
  """
  categoryName: String @fdc_generated(from: "Transaction.category", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Transaction`.`familyMember`. It must match the value of `FamilyMember`.`id`. See `@ref` for how to customize it.
  """
  familyMemberId: UUID! @fdc_generated(from: "Transaction.familyMember", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Transaction`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Transaction.user", purpose: IMPLICIT_REF_FIELD)
}
extend type UserSetting {
  """
  ✨ Implicit foreign key field based on `UserSetting`.`colorScheme`. It must match the value of `ColorScheme`.`id`. See `@ref` for how to customize it.
  """
  colorSchemeId: UUID @fdc_generated(from: "UserSetting.colorScheme", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `UserSetting`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "UserSetting.user", purpose: IMPLICIT_REF_FIELD)
}
extend type UserTypeFeature {
  """
  ✨ Implicit foreign key field based on `UserTypeFeature`.`userType`. It must match the value of `UserType`.`name`. See `@ref` for how to customize it.
  """
  userTypeName: String! @fdc_generated(from: "UserTypeFeature.userType", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `UserTypeFeature`.`feature`. It must match the value of `Feature`.`name`. See `@ref` for how to customize it.
  """
  featureName: String! @fdc_generated(from: "UserTypeFeature.feature", purpose: IMPLICIT_REF_FIELD)
}
