// Builds .env.local from the two files Firebase hands you, so none of the
// values are retyped by hand.
//
// Usage:
//   firebase apps:sdkconfig WEB --project <id> > web-config.json
//   node scripts/make-env.mjs web-config.json ~/Downloads/<service-account>.json
//
// The second argument is optional; without it you get the NEXT_PUBLIC_* half
// and placeholders for the admin half.
//
// WHY THIS EXISTS: the service account's private key is a multi-line PEM, and
// a .env file is line-based — so it has to be stored as one line with literal
// \n escapes (which lib/firebase-admin.ts converts back). Pasting the raw PEM
// out of the JSON is the single most common way this setup fails, and it
// fails with "Failed to parse private key", which does not point at the cause.
// Doing the escaping here removes the opportunity.

import { readFileSync, existsSync } from "node:fs";

const [webConfigPath, serviceAccountPath] = process.argv.slice(2);

if (!webConfigPath) {
  console.error(
    "usage: node scripts/make-env.mjs <web-config.json> [service-account.json]\n\n" +
      "  web-config.json      output of: firebase apps:sdkconfig WEB --project <id>\n" +
      "  service-account.json the key file downloaded from\n" +
      "                       Project settings > Service accounts > Generate new private key"
  );
  process.exit(1);
}

function readJson(path, label) {
  if (!existsSync(path)) {
    console.error(`Cannot find ${label}: ${path}`);
    process.exit(1);
  }
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    console.error(
      `${label} is not valid JSON: ${path}\n` +
        "If this came from apps:sdkconfig, make sure you redirected only stdout\n" +
        "and that the file does not still contain the CLI's progress spinner text."
    );
    process.exit(1);
  }
}

const rawWeb = readJson(webConfigPath, "web config");

// apps:sdkconfig prints the bare config object; with --json it wraps it in
// {status, result:{sdkConfig}}. Accept either, so it doesn't matter which
// form was captured.
const web = rawWeb.result?.sdkConfig ?? rawWeb.sdkConfig ?? rawWeb;

const REQUIRED = ["apiKey", "authDomain", "projectId", "storageBucket", "messagingSenderId", "appId"];
const missing = REQUIRED.filter((k) => !web[k]);
if (missing.length) {
  console.error(
    `Web config is missing: ${missing.join(", ")}\n\n` +
      "Expected the output of:  firebase apps:sdkconfig WEB --project <id>\n" +
      "If your project has no web app yet, create one first:\n" +
      '  firebase apps:create WEB "Finance Tracker Pro" --project <id>'
  );
  process.exit(1);
}

let admin = null;
if (serviceAccountPath) {
  const sa = readJson(serviceAccountPath, "service account key");
  if (sa.type !== "service_account" || !sa.private_key || !sa.client_email) {
    console.error(
      "That file does not look like a service account key.\n" +
        'It should be JSON containing "type": "service_account", client_email and private_key.'
    );
    process.exit(1);
  }
  if (sa.project_id && sa.project_id !== web.projectId) {
    // Mismatched halves produce a confusing runtime failure: sign-in succeeds
    // in the browser, then every token fails verification server-side.
    console.error(
      `Project mismatch — the web config is for "${web.projectId}" but the service\n` +
        `account key is for "${sa.project_id}". Use a key from the same project.`
    );
    process.exit(1);
  }
  admin = {
    projectId: sa.project_id ?? web.projectId,
    clientEmail: sa.client_email,
    // The one transformation that matters: real newlines to literal \n.
    privateKey: sa.private_key.replace(/\n/g, "\\n"),
  };
}

const lines = [
  "# Generated by scripts/make-env.mjs. Do not commit — this file is gitignored.",
  "",
  "# --- Firebase web app (client-side; safe to expose) ---",
  `NEXT_PUBLIC_FIREBASE_API_KEY=${web.apiKey}`,
  `NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${web.authDomain}`,
  `NEXT_PUBLIC_FIREBASE_PROJECT_ID=${web.projectId}`,
  `NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${web.storageBucket}`,
  `NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${web.messagingSenderId}`,
  `NEXT_PUBLIC_FIREBASE_APP_ID=${web.appId}`,
  "",
  "# --- Firebase Admin service account (server-side; SECRET) ---",
];

if (admin) {
  lines.push(
    `FIREBASE_PROJECT_ID=${admin.projectId}`,
    `FIREBASE_CLIENT_EMAIL=${admin.clientEmail}`,
    // Quoted so the literal \n sequences survive parsers that would otherwise
    // treat the value as ending at the first special character.
    `FIREBASE_PRIVATE_KEY="${admin.privateKey}"`
  );
} else {
  lines.push(
    "# Re-run with the service account key file to fill these in.",
    `FIREBASE_PROJECT_ID=${web.projectId}`,
    "FIREBASE_CLIENT_EMAIL=",
    'FIREBASE_PRIVATE_KEY=""'
  );
}

lines.push(
  "",
  "# --- Local emulators ---",
  "# false = talk to the real project above. Set to true, and also set the two",
  "# *_EMULATOR_HOST variables, to run fully locally instead.",
  "NEXT_PUBLIC_USE_FIREBASE_EMULATOR=false",
  "# FIREBASE_AUTH_EMULATOR_HOST=127.0.0.1:9199",
  "# DATA_CONNECT_EMULATOR_HOST=127.0.0.1:9499",
  ""
);

// Printed rather than written, so an existing .env.local is never clobbered
// without the person choosing to. They pipe it themselves.
process.stdout.write(lines.join("\n"));

const note = admin
  ? "Complete .env.local written to stdout."
  : "Partial .env.local written to stdout (admin half still needs the key file).";
process.stderr.write(`\n${note}\nRedirect it:  node scripts/make-env.mjs ... > .env.local\n`);
